// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BookCard: typeof import('./src/components/book-card/index.vue')['default']
    ChildrenPanel: typeof import('./src/components/comment/children-panel.vue')['default']
    Comment: typeof import('./src/components/comment/comment.vue')['default']
    LoadingAnimation: typeof import('./src/components/LoadingAnimation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleCard: typeof import('./src/components/SimpleCard.vue')['default']
    Slider: typeof import('./src/components/captcha/slider.vue')['default']
    StatusBar: typeof import('./src/components/StatusBar.vue')['default']
    Tag: typeof import('./src/components/tag/index.vue')['default']
    Textarea: typeof import('./src/components/comment/textarea.vue')['default']
    TextCollapsed: typeof import('./src/components/TextCollapsed.vue')['default']
  }
}
